kind: Service
apiVersion: v1
metadata:
  name: namegenservice
  labels:
    app: namegen
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: namegenservice
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: namegen
spec:
  selector:
    matchLabels:
      app: namegenservice
  template:
    metadata:
      labels:
        app: namegenservice
    spec:
      containers:
      - name: namegen
        image: christofferjerrebo/namegen-scratch
        env:
        - name: GENERATE_ERRORS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GENERATE_NAMEGEN_ERRORS
        ports:
        - name: http
          containerPort: 8080
