kind: Service
apiVersion: v1
metadata:
  name: numbergenservice
  labels:
    app: numbergen
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: numbergenservice
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: numbergen
spec:
  selector:
    matchLabels:
      app: numbergenservice
  template:
    metadata:
      labels:
        app: numbergenservice
    spec:
      containers:
      - name: numbergen
        image: christofferjerrebo/numbergen-scratch
        ports:
        - name: http
          containerPort: 8080
