kind: Service
apiVersion: v1
metadata:
  name: combinedgenservice
  labels:
    app: combinedgen
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
  selector:
    app: combinedgenservice
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: combinedgen
spec:
  template:
    metadata:
      labels:
        app: combinedgenservice
    spec:
      containers:
      - name: combinedgen
        image: christofferjerrebo/combinedgen-alpine
        ports:
        - name: http
          containerPort: 8080
