kind: Service
apiVersion: v1
metadata:
  name: namegenservice
  labels:
    app: namegen
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: namegenservice
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: namegen
spec:
  template:
    metadata:
      labels:
        app: namegenservice
    spec:
      containers:
      - name: namegen
        image: christofferjerrebo/namegen-scratch
        ports:
        - name: http
          containerPort: 8080
